### ISSUE TITLE
${env:MYVAR} not working in serverless.yml

### ISSUE THREAD

**Issue by ds17f** [neverendingqs/serverless-dotenv-plugin#10]
When I run in offline mode (`serverless-offline`) I'm unable to access the loaded `env` variables in my serverless.yml.  For example in the config below, the  `${env:STAGE}` always rolls over to the default.
```
# serverless.yml
service: serverless-framework-starter

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline #serverless-offline needs to be last in the list

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'
  serverless-offline:
    port: 4000
  dotenv:
    path: "./.env.${opt:NODE_ENV, 'development'}"

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE, 'dev'}
  region: ${env:REGION, 'us-east-1'}
  versionFunctions: false
  iamRoleStatements:
  -  Effect: "Allow"
     Action:
       - "s3:*"
     Resource: "*"

functions:
  test-func:
    handler: src/test-func/handler.default
    name: ${self:provider.stage}-${self:service}-upload
    memorySize: 128
    events:
      - http:
          path: hello
          method: get
          cors: true
```

The test handler has no trouble accessing `SOMEVAL` and it uses the proper value if I change the `NODE_ENV` at runtime.  
```
// handler.js
const hello = (event, context, callback) => {
  const response = {
    statusCode: 200,
    body: JSON.stringify({
      message: `Go Serverless v1.0! Your function executed successfully! ENV: ${process.env.SOMEVAL}`,
      input: event,
    }),
  };

  callback(null, response);

  // Use this code if you don't use the http event with the LAMBDA-PROXY integration
  // callback(null, { message: 'Go Serverless v1.0! Your function executed successfully!', event });
};

export default hello;
```

It seems like a timing issue.  It seems like the `serverless.yml` is processed before the `serverless-dotenv-plugin` is able to load the environment variables into scope.  Any idea how I can prove this or whether this is the right concept?

**Comment by ds17f** [comment]
Oh, yeah, if it helps: 

`.env.development`
```
STAGE=dev
REGION=us-east-1
SOMEVAL=dev val
HELLO_PATH=hello
```

`.env.production`
```
STAGE=prod
REGION=us-east-1
SOMEVAL=prod val
HELLO_PATH=hello_world
```

**Comment by andidev** [comment]
I have the same issue though it does not seem to be related to `serverless-offline`. I fail to run `serverless deploy`

**bash output**
```
> serverless deploy                                                                                

 Serverless Warning --------------------------------------

  A valid environment variable to satisfy the declaration 'env:COGNITO_USER_POOL_ARN' could not be found.


 Serverless Warning --------------------------------------

  A valid environment variable to satisfy the declaration 'env:COGNITO_USER_POOL_ARN' could not be found.

Serverless: DOTENV: Loading environment variables:
Serverless: 	 - COGNITO_USER_POOL_ARN
Serverless: 	 - COGNITO_USER_POOL_ID
Serverless: 	 - MONGODB_URI
Serverless: 	 - MONGODB_DATABASE
Serverless: 	 - SENTRY_DSN
```

**config**
```
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dotenv:
    path: .env-${self:provider.stage}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  iamRoleStatements:
    - Action:
        - cognito-idp:AdminGetUser
      Resource: ${env:COGNITO_USER_POOL_ARN}
      Effect: Allow
```

**Comment by orels1** [comment]
Have the same issue, and it's pretty annoying =(

**Comment by colynb** [comment]
It took me a while to figure out why I couldn't load env vars before the provider config, but then it dawned on me that there's no purpose to using hooks in the first place. Just load the env vars in the plugin constructor. Avoid hooks altogether!

A fix is coming soon.

**Comment by colynb** [comment]
I published a new version. Go ahead and give it another try. Thanks for your help!

**Comment by andidev** [comment]
@colynb 
Still no luck with version 1.2.0, seems that the env file is not found when pointing out the path to the env file dynamically like this:
```yaml
custom:
  dotenv:
    path: .env-${self:provider.stage}
```

also tried
```yaml
custom:
  dotenv:
    path: .env-${opt:stage, 'dev'}
```

it works when setting it statically:
```yaml
custom:
  dotenv:
    path: .env-dev
```

**Comment by colynb** [comment]
OK. I guess I misunderstood your specific problem. I did resolve a bigger
issue that's similar but I'll take a look at this further.

**Comment by andidev** [comment]
The problem that I mentioned is introduced in the 1.2.0 release. It worked in 1.1.3. Maybe I should have created a new issue.

**Comment by colynb** [comment]
@andidev I'm afraid that's a chicken and the egg problem. I may have introduced a breaking change. The question is, should the provider config load before the plugin loads the env vars, so that you can use the stage var to determine the path, or do you load env vars first thing so that you can use those in your provider config. I don't think you can have both.

**Comment by andidev** [comment]
Shouldn't at least the cli options, e.g. `${opt:stage}`, be available before the plugins load? Feels like there should be some way to achieve this. I would love to help but currently I have no time for this though. Thanks anyway for the fast response.

Seems like others got the same problem now after the latest release.
https://github.com/infrontlabs/serverless-dotenv-plugin/issues/19

**Comment by orels1** [comment]
@colynb That update fixed my issue! Thanks a lot.
